services:
  - type: web
    name: socialreddit
    env: static
    rootDir: frontend/reddit-frontend-starter
    buildCommand: npm install && npm run build
    staticPublishPath: dist

    routes:
      - type: rewrite
        source: /*
        destination: /index.html